# frozen_string_literal: true

require_relative "../error"
require_relative "flag"
require_relative "report_file"
require_relative "run"
require_relative "survivors"

class Kimera::CLI::Mutant
  OPTIONS = Kimera::FlagTable.new(
    banner: "Usage: kimera mutant ID|KEY --report REPORT.json",
    flags: [
      Kimera::Flag.build("--report FILE", :report, "Report generated by kimera run"),
      Kimera::Flag.build("--rerun", :rerun, "Re-evaluate only this mutant in the current project")
    ]
  )

  def initialize(io: $stdout, errors: $stderr)
    @io = io
    @errors = errors
  end

  def run(argv)
    options = { report: nil, rerun: false }
    id, = OPTIONS.parse(argv, options)
    show(identify(id, options), options)
  rescue Kimera::UsageError => error
    usage(error)
  end

  private

  def usage(error)
    @errors.puts("kimera: #{error.message}")
    1
  end

  def identify(id, options)
    raise(Kimera::UsageError, "mutant ID is required") unless id
    raise(Kimera::UsageError, "--report REPORT.json is required") unless options[:report]
    id
  end

  def show(id, options)
    report = options[:report]
    return rerun(id, report) if options[:rerun]
    Kimera::CLI::Survivors.new(io: @io, errors: @errors).run([report, "--id", id])
  end

  def rerun(id, report)
    document = Kimera::CLI::ReportFile.parse(report)
    row = locate(document, id)
    settings = provenance(document)
    @io.puts("Re-running mutant ##{row["mutant_id"]}: #{keyed(row)}")
    Kimera::CLI::Run.new(io: @io, errors: @errors).run(arguments_for(row, settings))
  end

  def locate(document, id)
    row = Kimera::CLI::ReportFile.row(document.fetch("results", []), id)
    raise(Kimera::UsageError, "no mutant ##{id} in this report") unless row
    raise(Kimera::UsageError, "mutant ##{id} has no source file") unless row["file"]
    row
  end

  def provenance(document)
    document["run"] ||
      raise(Kimera::UsageError, "report has no run provenance; rerun with a report created by this Kimera version")
  end

  def keyed(row)
    row["key"] ||
      raise(Kimera::UsageError, "report has no mutant keys; regenerate it with kimera run --report, then rerun")
  end

  def arguments_for(row, settings)
    [row.fetch("file"), "--focus", keyed(row), "--framework", settings.fetch("framework", "rspec")]
      .push("--source-root", settings["source_root"])
      .concat(Array(settings["tests"]).flat_map { |glob| ["--tests", glob] })
      .push("--operators", Array(settings["operators"]).join(","))
      .concat(modes(settings))
  end

  def modes(settings)
    [settings["coverage"] == false ? "--no-coverage" : nil, settings["isolated"] ? "--isolated" : nil].compact
  end
end
